# -*- coding: utf-8 -*-
"""Mohsin_64293_ai_assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AumOAcbuQBOHhk2KjUmYhUR3FQGx_ES_
"""

import pandas as pd
import random as random
df=pd.read_csv('test.csv')
id=df["id"]
nDf=pd.DataFrame(id)
array=[]
for r in id:
  array.append(random.randint(0,1))
nDf["target"]=array
nDf.to_csv('rnd.csv',index=False)